// Imports.jsx
import React, { useState, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  Send,
  Mic,
  Paperclip,
  X,
  FileText,
  File,
  LogOut,
  User,
  Languages,
  Download,
  Eye,
  Loader2,
  Upload,
  Bell,
  BellOff,
  Clock,
  DownloadCloud,
  TrendingUp,
  AlertTriangle,
  Info,
  Globe,
  Copy,
  MessageCircle,
  FileSymlink,
  Settings,
  EyeOff,
  Lock,
  LogIn,
  Shield,
  FileWarning,
  Type,
  Zap,
  Users,
  Building2,
  UserPlus,
  ChevronDown,
  AlertCircle,
  CheckCircle,
  Loader,
  Edit2,
  Trash2,
  Check,
  Search,
  Filter,
  ArrowLeft
} from "lucide-react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TimesheetForm from "./timesheet/TimesheetForm";
import TimesheetEntries from "./timesheet/TimesheetEntries";
import {
  useHomeLogic,
  notificationHelper,
  languages,
  formatFileSize,
} from "./HomeLogic";
import TimesheetOptions from "./timesheet/TimesheetOptions";
import { Document, Page, pdfjs } from "react-pdf";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";
import "react-pdf/dist/Page/AnnotationLayer.css";
import "react-pdf/dist/Page/TextLayer.css";
import { renderAsync } from "docx-preview";
import { loadNotoCJK } from "./utils/loadNotoCJK";
import { previewCJKPdf } from "./utils/previewCJKPdf";
import docxPdf from "docx-pdf";
import { Packer, Paragraph, TextRun } from "docx";
import { PDFDocument, rgb } from "pdf-lib";
import { toast } from "react-toastify";

export {
  React,
  useState,
  useRef,
  useEffect,
  useNavigate,
  Send,
  Mic,
  Paperclip,
  X,
  FileText,
  File,
  LogOut,
  User,
  Languages,
  Download,
  Eye,
  Loader2,
  Upload,
  Bell,
  BellOff,
  Clock,
  DownloadCloud,
  TrendingUp,
  AlertTriangle,
  Info,
  Globe,
  Copy,
  MessageCircle,
  FileSymlink,
  ToastContainer,
  TimesheetForm,
  TimesheetEntries,
  useHomeLogic,
  notificationHelper,
  languages,
  formatFileSize,
  TimesheetOptions,
  Document,
  Page,
  pdfjs,
  pdfjsLib,
  renderAsync,
  loadNotoCJK,
  previewCJKPdf,
  docxPdf,
  Packer,
  Paragraph,
  TextRun,
  PDFDocument,
  rgb,
  toast,
  Shield,
  FileWarning,
  Type,
  Zap,
  Settings,
  Users,
  Building2,
  UserPlus,
  ChevronDown,
  AlertCircle,
  CheckCircle,
  Loader,
  EyeOff,
  Lock,
  LogIn,
  Edit2,
  Trash2,
  Check,
  Search,
  Filter,
  ArrowLeft
};